name: Push Workflow

# Trigger on push to the main or develop branches
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "select the branch name"
        required: true
        default: " "
        type: string
  pull_request:
    branches: [main, hotfix-*]

jobs:
  deploy-QA:
    name: Deploy to QA
    uses: ashwin-naini/githubactions/.github/workflows/pullrequest.yml@refs/heads/test

    
