name: Push Workflow

# Trigger on push to the main or develop branches
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "select the branch name"
        required: true 
        default: "  "
        type: string
  push:
    branches: [main]

jobs:
  print-info:
    # Define the operating system for the runner
    runs-on: ubuntu-latest

    steps:
      - name: Print Push Information
        run: |
          # Print the branch name where the push occurred
          echo "Branch Name: ${{ github.event.inputs.branch }}"
          # Print the commit message of the last commit
          echo "Commit Message: ${{ github.event.head_commit.message }}"
          # printh the actor name
          echo "github username: ${{github.actor}}"
